package com.yuranium.core;

import java.io.Serializable;

public enum MessageType implements Serializable
{
    APPROVE_ORDER_COMMAND,
    CANCEL_GOOD_RESERVE_COMMAND,
    CANCEL_PAYMENT_COMMAND,
    GOOD_COMPLETE_RESERVE_COMMAND,
    GOOD_RESERVE_COMMAND,
    PAY_GOODS_COMMAND,
    REJECT_ORDER_COMMAND,

    GOOD_COMPLETE_RESERVE_EVENT,
    GOOD_FAILED_COMPLETE_RESERVE_EVENT,
    GOOD_RESERVE_CANCELLED_EVENT,
    GOOD_RESERVED_EVENT,
    GOOD_RESERVE_FAILED_EVENT,
    ORDER_CREATED_EVENT,
    ORDER_REJECTED_EVENT,
    ORDER_STATUS_CHANGED_EVENT,
    PAYMENT_FAILED_EVENT,
    PAYMENT_SUCCESSFUL_EVENT
}