spring:
  application:
    name: good-service
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:good-db
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create