server:
  port: 8080

spring:
  application:
    name: order-service
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:order-db
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      properties:
        enable:
          idempotence: true
      acks: all

    consumer:
      group-id: ${spring.application.name}
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: com.yuranium.core.*

    topic-names:
      order: order-events-topic
      order-command: order-command-topic
      good: good-events-topic
      payment: payment-events-topic